# Generated by Django 5.2.4 on 2025-08-04 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_contribution_submittednews_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittednews',
            old_name='submitted_by',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='submittednews',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='submittednews',
            name='title',
        ),
        migrations.AddField(
            model_name='submittednews',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
