# Generated by Django 5.2.4 on 2025-08-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_rename_submitted_by_submittednews_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='submittednews',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='submittednews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='submittednews',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='submittednews',
            name='is_fake',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submittednews',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submittednews',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
