# Generated by Django 5.2.4 on 2025-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_alter_contribution_user_alter_news_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='title',
            field=models.CharField(default='Untitled contribution', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submittednews',
            name='title',
            field=models.CharField(default='Untitled submitted news', max_length=255),
            preserve_default=False,
        ),
    ]
