# Generated by Django 5.2.4 on 2025-08-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_contribution_title_submittednews_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submittednews',
            options={'ordering': ['-created_at']},
        ),
    ]
